language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-5
before_install:
    # Installing xtext etc. as a dependency
    - cd ..
    - pip install jinja2
    - pip install arpeggio
    - git clone --depth=1 --branch=master https://github.com/goto40/textX.git
    - cd textX && python setup.py install
    - cd ../itemlang
install:
    - python setup.py install
script:
    - py.test tests
    - cd system_tests
    - sh run.sh