language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
    # Installing textx etc. as a dependency
    - cd ..
    # stuff for the python
    - pip install jinja2
    - pip install arpeggio
    - pip install pytest
    - pip install numpy
    # stuff for compiling cpp
    - sudo apt-get install -qq catch
    #- sudo apt-get install -qq libmsgsl-dev
    - git clone --depth=1 --branch=master https://github.com/igordejanovic/textX
    - cd textX && python setup.py install
    - cd ../itemlang
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
    - python setup.py install
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
    - py.test tests
    - cd system_tests
    - sh run.sh