package types {
    type int        as signed   with 32 bits
    type float      as float    with 32 bits

    type FLOAT32    as float    with 32 bits
    type FLOAT64    as float    with 64 bits
    type FLOAT128   as float    with 128 bits

    type UINT8      as unsigned with 8  bits
    type UINT16     as unsigned with 16 bits
    type UINT32     as unsigned with 32 bits
    type UINT64     as unsigned with 64 bits

    type SINT8      as signed   with 8  bits
    type SINT16     as signed   with 16 bits
    type SINT32     as signed   with 32 bits
    type SINT64     as signed   with 64 bits
}
